Restored failure mode to ensure ghl_abort_if_error() is tested

diff --git a/.github/workflows/github-actions-MacOS-gcc.yml b/.github/workflows/github-actions-MacOS-gcc.yml
--- a/.github/workflows/github-actions-MacOS-gcc.yml
+++ b/.github/workflows/github-actions-MacOS-gcc.yml
@@ -330,10 +330,13 @@ jobs:
           curl -O https://stellarcollapse.org/EOS/SLy4_3335_rho391_temp163_ye66.h5.bz2 && bunzip2 SLy4_3335_rho391_temp163_ye66.h5.bz2
       - name: Run unit test for error-catching
         run: |
-          for i in {0..82}
-          do
-            ./test/unit_test_code_error "$i"
-          done
+          for i in {0..82}; do
+            if ./test/unit_test_code_error "$i"; then
+              echo "Failed to fail!"
+              exit 1
+            else
+              echo "Failed successfully!"
+            fi
       - name: Generate coverage report
         uses: ./.github/actions/code-coverage
         with:
diff --git a/.github/workflows/github-actions-Ubuntu-intel.yml b/.github/workflows/github-actions-Ubuntu-intel.yml
--- a/.github/workflows/github-actions-Ubuntu-intel.yml
+++ b/.github/workflows/github-actions-Ubuntu-intel.yml
@@ -335,9 +335,13 @@ jobs:
       - name: Run unit test for error-catching
         run: |
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib
-          for i in {0..82}
-          do
-            ./test/unit_test_code_error "$i"
+          for i in {0..82}; do
+            if ./test/unit_test_code_error "$i"; then
+              echo "Failed to fail!"
+              exit 1
+            else
+              echo "Failed successfully!"
+            fi
           done
 #      - name: Generate coverage report
 #        uses: ./.github/actions/code-coverage
